### ISSUE TITLE
Advisor's degree not generating

### ISSUE THREAD

**Issue by jtelliott** [Auburngrads/DODschools#5]
<img width="685" alt="screen shot 2018-01-30 at 12 43 43 pm" src="https://user-images.githubusercontent.com/11259515/35581925-4251d212-05bb-11e8-9cf7-b5739ace8b9b.png">
In `metadata.yml`, I have my advisor's degree listed (PhD), but when I knit the document, nothing shows up after his name. However, the other committee members' information shows up just fine.

```
advisor:
  name: 'Raymond R. Hill'
  department: 'ENS' # Use three-letter designator
  rank: 'Civilian'
  service: 'usaf' # Use abbreviation - leave blank if NA
  currentDegree: 'PhD'
  phone: '937-255-3636 x7469'
  email: "raymond.hill@afit.edu"
```
