### ISSUE TITLE
Extra Committee Member

### ISSUE THREAD

**Issue by jtelliott** [Auburngrads/DODschools#7]
For some reason, I cannot get the third committee member to go away. I've tried both commenting and removing the references from the yaml header, but they still show. Commenting works on my advisor's rank, but not the actual reader, for some reason. I have also commented out the corresponding sections of the `metadata.yml` file.

Output:

<img width="658" alt="screen shot 2018-02-09 at 1 53 36 pm" src="https://user-images.githubusercontent.com/11259515/36044445-b80fab90-0da0-11e8-876f-2c44df2dcbc2.png">

Code:

```r
advisor:
  name:       "`r DODschools::noTouch('metadata.yml')$advisor$name`"
  department: "`r DODschools::noTouch('metadata.yml')$advisor$department`"
#  rank:       "`r DODschools::noTouch('metadata.yml')$advisor$rank`"
  service:    "`r DODschools::noTouch('metadata.yml')$advisor$service`"
  prevdegree: "`r DODschools::noTouch('metadata.yml')$advisor$currentDegree`"
  phone:      "`r DODschools::noTouch('metadata.yml')$advisor$phone`"
  email:      "`r DODschools::noTouch('metadata.yml')$advisor$email`"
reader1:
  name:       "`r DODschools::noTouch('metadata.yml')$reader1$name`"
  department: "`r DODschools::noTouch('metadata.yml')$reader1$dept`"
  rank:       "`r DODschools::noTouch('metadata.yml')$reader1$rank`"
  service:    "`r DODschools::noTouch('metadata.yml')$reader1$service`"
  prevdegree: "`r DODschools::noTouch('metadata.yml')$reader1$currentDegree`"
# reader2:
#   name:       "`r DODschools::noTouch('metadata.yml')$reader2$name`"
#   department: "`r DODschools::noTouch('metadata.yml')$reader2$dept`"
#   rank:       "`r DODschools::noTouch('metadata.yml')$reader2$rank`"
#   service:    "`r DODschools::noTouch('metadata.yml')$reader2$service`"
#   prevdegree: "`r DODschools::noTouch('metadata.yml')$reader2$currentDegree`"
# reader3:
#   name:       "`r DODschools::noTouch('metadata.yml')$reader3$name`"
#   department: "`r DODschools::noTouch('metadata.yml')$reader3$dept`"
#   rank:       "`r DODschools::noTouch('metadata.yml')$reader3$rank`"
#   service:    "`r DODschools::noTouch('metadata.yml')$reader3$service`"
#   prevdegree: "`r DODschools::noTouch('metadata.yml')$reader3$currentDegree`"
```

**Comment by Auburngrads** [comment]
I'll probably change the way this works in a future update.  For now, you can delete the `reader2` and `reader3` sections from the `metadata.yml` file.  Also, leave the yaml header in your thesis document as-is.

**Comment by jtelliott** [comment]
Huh. That did not change anything. `metadata.yml` currently looks like this:

```
advisor:
  name: 'Raymond R. Hill'
  department: 'ENS' # Use three-letter designator
  rank: 
  service: 'usaf' # Use abbreviation - leave blank if NA
  currentDegree: 'PhD'
  phone: '937-255-3636 x7469'
  email: "raymond.hill@afit.edu"
reader1:
  name: 'Thomas P. Talafuse'  # First Reader
  department: 'ENS' # Use three-letter designator
  rank: 'Major'
  service: 'usaf' # Use abbreviation - leave blank if NA
  currentDegree: 'PhD'
document:
  title: "Air Force Officer Attrition: An Econometric Analysis"
  designator: 'AFIT-ENS-MS-18-M-118'
  pages: 30
  keywords: 'LaTeX,Thesis,typesetting'
  type: 'Thesis'
```

And the output hasn't changed at all. I'm have another copy of the document, so I'll make sure I'm knitting and editing the correct one.
